# Generated by Django 4.0.5 on 2022-07-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answer_id', models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='answer_id')),
                ('user_id', models.CharField(max_length=256, verbose_name='사용자')),
                ('test_id', models.SmallIntegerField(verbose_name='test_id')),
                ('v_type', models.CharField(max_length=256, verbose_name='시각화종류')),
                ('v_task', models.CharField(max_length=256, verbose_name='task')),
                ('answer', models.CharField(max_length=64, verbose_name='답안')),
                ('status', models.BooleanField(verbose_name='정답여부')),
                ('time', models.CharField(max_length=64, verbose_name='소요시간')),
            ],
            options={
                'verbose_name': '답안',
                'verbose_name_plural': '답안',
                'db_table': 'Vis_Answer',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('choice_id', models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='choice_id')),
                ('user_id', models.CharField(max_length=256, verbose_name='사용자')),
                ('set_number', models.CharField(max_length=256, verbose_name='set_number')),
                ('choice_type', models.CharField(max_length=256, verbose_name='선호 시각화')),
                ('v_task', models.CharField(max_length=256, verbose_name='task')),
                ('v_reason', models.CharField(max_length=256, verbose_name='선택이유')),
                ('time', models.CharField(max_length=64, verbose_name='소요시간')),
            ],
            options={
                'verbose_name': '선택 결과',
                'verbose_name_plural': '선택 결과',
                'db_table': 'Vis_Choice_Result',
            },
        ),
        migrations.CreateModel(
            name='Vis_Choice_Test',
            fields=[
                ('vis_id', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='vis_id')),
                ('set_number', models.CharField(max_length=256, verbose_name='set_number')),
                ('vis_title', models.CharField(max_length=256, verbose_name='시각화제목')),
                ('v_task', models.CharField(max_length=256, verbose_name='task')),
                ('v_question', models.CharField(max_length=256, verbose_name='질문')),
                ('vis_1', models.CharField(max_length=64, verbose_name='보기1')),
                ('vis_2', models.CharField(max_length=64, verbose_name='보기2')),
            ],
            options={
                'verbose_name': '선택지',
                'verbose_name_plural': '선택지',
                'db_table': 'Vis_Choice_Test',
            },
        ),
        migrations.CreateModel(
            name='Vis_test',
            fields=[
                ('test_id', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='test_id')),
                ('v_number', models.SmallIntegerField(verbose_name='문제번호')),
                ('v_title', models.CharField(max_length=256, verbose_name='시각화제목')),
                ('v_type', models.CharField(max_length=256, verbose_name='시각화종류')),
                ('v_task', models.CharField(max_length=256, verbose_name='task')),
                ('title', models.CharField(max_length=256, verbose_name='문제제목')),
                ('examples_1', models.CharField(max_length=64, verbose_name='보기1')),
                ('examples_2', models.CharField(max_length=64, verbose_name='보기2')),
                ('examples_3', models.CharField(blank=True, max_length=64, null=True, verbose_name='보기3')),
                ('examples_4', models.CharField(blank=True, max_length=64, null=True, verbose_name='보기4')),
                ('correct', models.CharField(max_length=64, verbose_name='정답')),
            ],
            options={
                'verbose_name': '시각화 테스트',
                'verbose_name_plural': '시각화 테스트',
                'db_table': 'Vis_Test',
            },
        ),
    ]
