# Generated by Django 4.0.5 on 2022-08-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vis_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('user_id', models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='사용자')),
                ('sex', models.CharField(max_length=256, verbose_name='성별')),
                ('age', models.CharField(max_length=256, verbose_name='나이')),
                ('major', models.CharField(max_length=256, verbose_name='전공')),
                ('education', models.CharField(max_length=256, verbose_name='최종학력')),
            ],
            options={
                'verbose_name': '사용자 정보',
                'verbose_name_plural': '사용자 정보',
                'db_table': 'User_info',
            },
        ),
        migrations.CreateModel(
            name='Vis_prefer',
            fields=[
                ('vis_prefer_id', models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='vis_prefer_id')),
                ('prefer_id', models.SmallIntegerField(verbose_name='prefer_id')),
                ('user_id', models.CharField(max_length=256, verbose_name='사용자')),
                ('vis_type', models.CharField(max_length=256, verbose_name='시각화 종류')),
                ('v_task', models.CharField(max_length=256, verbose_name='task')),
                ('prefer', models.IntegerField(verbose_name='정답 선호도')),
            ],
            options={
                'verbose_name': '정답 선호도 결과',
                'verbose_name_plural': '정답 선호도 결과',
                'db_table': 'Vis_prefer',
            },
        ),
    ]
