# Generated by Django 4.0.5 on 2022-07-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vis_app', '0002_user_info_vis_prefer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='user_info_id',
        ),
        migrations.AlterField(
            model_name='user_info',
            name='user_id',
            field=models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='사용자'),
        ),
    ]
