# Generated by Django 4.0.5 on 2022-07-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vis_app', '0003_remove_user_info_user_info_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vis_prefer',
            name='prefer_id',
            field=models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='prefer_id'),
        ),
    ]
