# Generated by Django 4.0.5 on 2022-06-10 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='사용자 ID')),
                ('name', models.CharField(max_length=32, verbose_name='사용자 이름')),
                ('email', models.CharField(max_length=256, verbose_name='사용자 이메일')),
                ('password', models.CharField(max_length=64, verbose_name='사용자 비밀번호')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자',
                'db_table': 'User',
            },
        ),
    ]
